export const FILM_LIST_ROUTE = "/"
export const FILM_ITEM_ROUTE = "/item"
export const FILM_FAVORITES_ROUTE = "/favorites"
export const FILM_COMPARE_ROUTE = "/compare"
export const FAVORITES_KEY = "favorites"
export const COMPARE_KEY = "compare"